### ISSUE TITLE
Generate GitHub releases for gem changes

### ISSUE THREAD

**Issue by addersuk** [simplybusiness/twiglet-ruby#51]
## What

We want to use the GitHub releases function to improve visablity to automatically generate the release notes for each version of a gem

## Why

To improve the visibility of the changes in each version and make it easier for everyone to access if to upgrade

## How

We need to use a GitHub Action in the pipeline to create the release using the version from the version.rb file.

https://github.com/actions/create-release

## ACs

- [x] We have a release with a version that matches the version.rb file
- [x] It has auto generated release notes based on included PRs

**Comment by moltenice** [comment]
https://github.com/simplybusiness/approved-github-actions/pull/15

**Comment by moltenice** [comment]
Initial working solution:

Need to manually specify:

1. `master` to the default branch
2. Gem name instead of `Example` in `Example::VERSION`

```yaml
name: Create GitHub Release

on:
  push:
    branches:
      - "master"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Get Ruby Version
        id: get-ruby-version
        run: echo "::set-output name=RUBY_VERSION::$(bundle exec ruby -e 'puts Example::VERSION')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.get-ruby-version.outputs.RUBY_VERSION }}
```

**Comment by moltenice** [comment]
Updated working solution with no new action requirements.

Still need to manually specify:

1. `master` to the default branch
2. Gem name instead of `Example` in `Example::VERSION`

```yaml
name: Create GitHub Release

on:
  push:
    branches:
      - "master"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Get Gem Version
        id: get-gem-version
        run: echo "::set-output name=GEM_VERSION::$(bundle exec ruby -e 'puts Example::VERSION')"
      - name: Create Release
        uses: actions/github-script@v5
        env:
          GEM_VERSION: ${{ steps.get-gem-version.outputs.GEM_VERSION }}
        with:
          result-encoding: string
          script: |
            const { GEM_VERSION } = process.env
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: GEM_VERSION,
              generate_release_notes: true,
            })
```
